# yaml-language-server: $schema=null
title: "Matthias Brat"
description: "A blog and documentation site"
base_url: "https://matthiasbrat.com"
dev_base_url: "http://localhost:3000" # Base URL for local development
default_social_image: "/me.jpg"

# Google OAuth (for reactions)
# Create a .env file with:
#   GOOGLE_CLIENT_ID=your-client-id
#   GOOGLE_CLIENT_SECRET=your-client-secret
# See .env.example for template

# Profile
profile:
  photo: "/me.jpg"
  bio: "Monitoring Developer @ European Commission"
  github: "https://github.com/Matthiasbrat"
  linkedin: "https://www.linkedin.com/in/matthias-brat"

# Referrals (people I recommend)

